"""initial schema: recipe_jobs, job_events, app_settings

Revision ID: d441a46c776d
Revises: 
Create Date: 2026-07-11 14:33:31.549811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd441a46c776d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('recipe_jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shortcode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DOWNLOADING', 'TRANSCRIBING', 'OCR', 'VISION', 'RECONSTRUCTING', 'VALIDATING', 'EXPORTING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('video_metadata', sa.Text(), nullable=True),
    sa.Column('raw_transcript', sa.Text(), nullable=True),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('raw_vision', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('structured_recipe', sa.Text(), nullable=True),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('validation_report', sa.Text(), nullable=True),
    sa.Column('export_results', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_jobs_shortcode'), ['shortcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_jobs_url'), ['url'], unique=False)

    op.create_table('job_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'COMPLETED', 'FAILED', 'SKIPPED', name='eventstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['recipe_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_events_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_events_stage'), ['stage'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_events_stage'))
        batch_op.drop_index(batch_op.f('ix_job_events_job_id'))

    op.drop_table('job_events')
    with op.batch_alter_table('recipe_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_jobs_url'))
        batch_op.drop_index(batch_op.f('ix_recipe_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_recipe_jobs_shortcode'))

    op.drop_table('recipe_jobs')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
